"""Database layer.

Defines the SQLAlchemy engine, the session factory, and the ``AnalysisResult``
model — the single source of truth for each screening job. Both the API process
and the Celery worker import from here; they share state only through this DB
(there is no direct call between the two processes).
"""
import os
from datetime import datetime
from dotenv import load_dotenv  # <--- Important for local development
from sqlalchemy import create_engine, Column, String, Text, DateTime, JSON, text
from sqlalchemy.orm import sessionmaker, declarative_base

# Load environment variables (so it can read the URL from .env file)
load_dotenv()

# Database address
# Default is localhost to make debugging easier, in Docker it will take from ENV
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql+psycopg://ai:ai@localhost:5432/hiremesh")
# 2. Critical fix: Replace the prefix to use the Psycopg 3 driver you installed
if DATABASE_URL and DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg://", 1)

# 1. Engine improvement for Scalability
engine = create_engine(
    DATABASE_URL,
    pool_size=10,
    max_overflow=20,
    pool_pre_ping=True
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class AnalysisResult(Base):
    """One row per resume-screening job.

    Created by the API (status ``pending``) when a resume is uploaded, then
    updated by the worker as it moves to ``processing`` and finally
    ``completed`` / ``failed``. ``session_id`` is the handle the client polls on
    and the same id handed to the worker.
    """

    __tablename__ = "analysis_results"

    # UUID generated by the API; primary key and the handle the client polls on.
    session_id = Column(String, primary_key=True, index=True)
    status = Column(String, default="pending")  # pending, processing, completed, failed

    job_description = Column(Text, nullable=True)

    # Raw extracted resume text — kept so follow-up Q&A can ground answers in
    # the actual CV, not only the evaluation summary.
    resume_text = Column(Text, nullable=True)

    # Results (plain text + structured metadata in JSON)
    result_text = Column(Text, nullable=True)
    result_metadata = Column(JSON, nullable=True)

    # 2. Adding timestamps - critical for debugging
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


def init_db():
    """Create tables if missing and apply lightweight column migrations.

    Called once on API startup.
    """
    # Checks and creates tables if they don't exist
    Base.metadata.create_all(bind=engine)

    # Lightweight self-healing migration: create_all() never ALTERs an existing
    # table, and this project has no Alembic. So ensure columns added after the
    # table first existed are present. Idempotent (IF NOT EXISTS), runs cheaply
    # on every startup. Postgres-specific syntax (this app targets Postgres).
    with engine.begin() as conn:
        conn.execute(text(
            "ALTER TABLE analysis_results ADD COLUMN IF NOT EXISTS resume_text TEXT"
        ))